### ISSUE TITLE
`saber info` command error

### ISSUE THREAD

**Issue by zcaiElvis** [hallamlab/SABer#8]
When using `saber info` command, and error pop up.

> Traceback (most recent call last):
  File "/home/elvis/anaconda3/envs/saber_env/bin/saber", line 8, in <module>
    sys.exit(main())
  File "/home/elvis/anaconda3/envs/saber_env/lib/python3.8/site-packages/saber/__main__.py", line 45, in main
    cmd(sys.argv[2:])
  File "/home/elvis/anaconda3/envs/saber_env/lib/python3.8/site-packages/saber/commands.py", line 33, in info
    py_deps = {x.split('==')[0]:x.split('==')[1] for x in freeze.freeze()}
  File "/home/elvis/anaconda3/envs/saber_env/lib/python3.8/site-packages/saber/commands.py", line 33, in <dictcomp>
    py_deps = {x.split('==')[0]:x.split('==')[1] for x in freeze.freeze()}
IndexError: list index out of range

Environment: saber_env on Ubuntu 20.04

**Comment by RyloByte** [comment]
I'll take a look at this this week.  Not sure what's going on, but I'm sure it's a pretty quick fix.
